# Generated by Django 3.2.18 on 2023-03-29 12:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20230329_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 3, 29, 12, 1, 28, 851186, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
